name: Run Unit Tests
on:
  push:
    branches:
      - main 
jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Run tests
        run: |
          python -m unittest discover -p "*.py"

  windows-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Run tests
        run: |
          python -m unittest discover -p "*.py"
